name = "mtloveapi"
main = "src/worker.js"
compatibility_date = "2025-02-01"
workers_dev = true
preview_urls = false
routes = [
	{ pattern="https://mtloveapi.hdcola.org/*", custom_domain=true}
]


[observability]
enabled = true
